import os

APP_ENV = os.environ.get('APP_ENV')
WEBAPP_AWS_COGNITO_REGION = os.environ.get('WEBAPP_AWS_COGNITO_REGION')
WEBAPP_AWS_COGNITO_USER_POOL_ID = os.environ.get('WEBAPP_AWS_COGNITO_USER_POOL_ID')
WEBAPP_REACT_HOST = os.environ.get('WEBAPP_REACT_HOST')
LARAVEL_API_HOST = os.environ.get('LARAVEL_API_HOST')
